### ISSUE TITLE
Infinite loop in from_fsm() on Python 2

### ISSUE THREAD

**Issue by davidwagner** [qntm/greenery#32]
Converting the following simple 2-state automaton into a regexp causes an infinite recursion, when run on Python 2.7:

    from greenery import fsm
    from greenery import lego
    f = fsm.fsm(alphabet={'a','b'}, states={0,1}, initial=0, finals={0}, map={0: {'a':0, 'b':1}, 1: {'a':1, 'b':0}})
    print(f)
    l = lego.from_fsm(f)
    print(l)

In particular, I get a `maximum recursion depth exceeded` error when running `from_fsm()` in the script above, on Python 2.7:

    Traceback (most recent call last):
      File "testlego.py", line 5, in <module>
        l = lego.from_fsm(f)
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 159, in from_fsm
        return brz[f.initial][outside].reduce()
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 44, in new_method
        result = method(self, *args, **kwargs)
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 1441, in reduce
        reduced = [m.reduce() for m in self.mults]
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 44, in new_method
        result = method(self, *args, **kwargs)
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 1277, in reduce
        reduced = self.multiplicand.reduce()
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 47, in new_method
        return result.reduce()
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 47, in new_method
        return result.reduce()
    [repeats many times]
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 47, in new_method
        return result.reduce()
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 44, in new_method
        result = method(self, *args, **kwargs)
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 1719, in reduce
        if reduced != self.concs:
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 1395, in __eq__
        return self.mults == other.mults
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 1160, in __eq__
        and self.multiplier == other.multiplier
      File ".local/lib/python2.7/site-packages/greenery/lego.py", line 990, in __eq__
        return self.min == other.min and self.max == other.max
    RuntimeError: maximum recursion depth exceeded

I'm using Python 2.7:

    $ python
    Python 2.7.13 (default, Jan 12 2017, 17:59:37)
    [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)] on linux2

When I run the same script with Python 3.5, it works fine.  Python's `sys.getrecursionlimit()` returns 1000 for both Python 2 and Python 3 on my platform.  I installed greenery via `pip --user`, and I have version 3.0 of the greenery library (the latest that Pip could find).

**Comment by qntm** [comment]
I'm so sorry that it took me this long to see your issues, until now my GitHub email account was one I do not frequently check.

I'm also very sorry to say that `greenery` only supports Python 3.x, not Python 2.x. I apologise for not signalling this at all in the README. I will fix this now.

**Comment by qntm** [comment]
[README updated](https://github.com/qntm/greenery/commit/2fb70ce9b17e1522b7c324c87847d3a5ed2ceeeb).
